import { IUserInfo } from '@/components/MyPage/Profile/ProfileModifyForm';

export const patientInfoList: IUserInfo[] = [
  {
    label: '이름',
    key: 'name',
    value: '김환자',
    placeholder: '이름을 입력해주세요',
    type: 'text',
  },
  {
    label: '나이',
    key: 'age',
    value: '',
    placeholder: '나이를 입력해주세요',
    type: 'text',
  },
  {
    label: '주소',
    key: 'address.addr',
    value: '',
    placeholder: '주소 찾기 버튼으로 검색해주세요',
    type: 'address',
  },
  {
    label: '전화번호',
    key: 'contact',
    value: '',
    placeholder: '전화번호를 입력해주세요',
    type: 'text',
  },
  {
    label: '상세 주소',
    key: 'address.addrDetail',
    value: '',
    placeholder: '상세 주소를 작성해주세요',
    type: 'text',
  },
  {
    label: '성별',
    key: 'gender',
    value: '남',
    placeholder: '성별을 선택해주세요',
    type: 'select',
    options: ['남', '여'],
  },
  {
    label: '우편번호',
    key: 'address.zipCode',
    value: '',
    placeholder: '주소 찾기 버튼으로 검색해주세요',
    type: 'zipCode',
  },
  {
    label: '보호자',
    key: 'nokName',
    value: '',
    placeholder: '보호자 이름을 입력해주세요',
    type: 'text',
  },
  {
    label: '간병 요구사항',
    key: 'careRequirements',
    value: '',
    placeholder: '요구사항을 작성해주세요',
    type: 'text',
  },
  {
    label: '보호자 전화번호',
    key: 'nokContact',
    value: '',
    placeholder: '전화번호를 입력해주세요',
    type: 'text',
  },
  {
    label: '환자 특이사항',
    key: 'patientSignificant',
    value: '',
    placeholder: '특이사항을 작성해주세요',
    type: 'text',
  },

  {
    label: '희망 간병 시작일',
    key: 'wantCareStartDate',
    value: '',
    placeholder: '희망하는 시작일을 선택해주세요',
    type: 'date',
  },
  {
    label: '간병 장소',
    key: 'realCarePlace',
    value: '',
    placeholder: '간병받을 장소를 입력해주세요',
    type: 'text',
  },
  {
    label: '희망 간병 종료일',
    key: 'wantCareEndDate',
    value: '',
    placeholder: '희망하는 종료일을 선택해주세요',
    type: 'date',
  },
];

export const caregiverInfoList: IUserInfo[] = [
  {
    label: '이름',
    key: 'name',
    value: '김간병',
    placeholder: '이름을 입력해주세요',
    type: 'text',
  },
  {
    label: '나이',
    key: 'age',
    value: '',
    placeholder: '나이를 입력해주세요',
    type: 'text',
  },
  {
    label: '주소',
    key: 'address.addr',
    value: '',
    placeholder: '주소 찾기 버튼으로 검색해주세요',
    type: 'address',
  },
  {
    label: '경력',
    key: 'experienceYears',
    value: '',
    placeholder: '경력을 입력해주세요',
    type: 'text',
  },
  {
    label: '상세 주소',
    key: 'address.addrDetail',
    value: '',
    placeholder: '상세 주소를 작성해주세요',
    type: 'text',
  },
  {
    label: '전화번호',
    key: 'contact',
    value: '',
    placeholder: '전화번호를 입력해주세요',
    type: 'text',
  },
  {
    label: '우편번호',
    key: 'address.zipCode',
    value: '',
    placeholder: '주소 찾기 버튼으로 검색해주세요',
    type: 'zipCode',
  },
  {
    label: '성별',
    key: 'gender',
    value: '남',
    placeholder: '성별을 선택해주세요',
    type: 'select',
    options: ['남', '여'],
  },
  {
    label: '등록증',
    key: 'specialization',
    value: '',
    placeholder: '등록증 번호를 입력해주세요',
    type: 'text',
  },
  {
    label: '특이사항',
    key: 'caregiverSignificant',
    value: '',
    placeholder: '특이사항을 작성해주세요',
    type: 'text',
  },
  {
    label: '희망 간병 시작일',
    key: 'wantCareStartDate',
    value: '',
    placeholder: '희망하는 시작일을 선택해주세요',
    type: 'date',
  },
  {
    label: '희망 간병 종료일',
    key: 'wantCareEndDate',
    value: '',
    placeholder: '희망하는 종료일을 선택해주세요',
    type: 'date',
  },
];
